# Generated by Django 6.0.6 on 2026-06-18 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_text', models.TextField(blank=True, verbose_name='Расписание (текст)')),
                ('schedule_file', models.FileField(blank=True, null=True, upload_to='program/schedule/', verbose_name='Расписание (файл)')),
                ('speakers_text', models.TextField(blank=True, verbose_name='Спикеры (текст)')),
                ('speakers_file', models.FileField(blank=True, null=True, upload_to='program/speakers/', verbose_name='Спикеры (файл)')),
                ('map_schema', models.FileField(blank=True, null=True, upload_to='program/map/', verbose_name='Схема (карта)')),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='events.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
            },
        ),
        migrations.CreateModel(
            name='DayProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('schedule_text', models.TextField(blank=True, verbose_name='Расписание дня (текст)')),
                ('schedule_file', models.FileField(blank=True, null=True, upload_to='day_program/schedule/', verbose_name='Расписание дня (файл)')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='events.program', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Программа дня',
                'verbose_name_plural': 'Программы дней',
                'ordering': ('date',),
            },
        ),
    ]
