# Generated by Django 6.0.6 on 2026-06-18 17:21

import events.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayprogram',
            name='schedule_file',
            field=events.fields.HashedFileField(blank=True, null=True, upload_to='day_program/schedule/', verbose_name='Расписание дня (файл)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='map_schema',
            field=events.fields.HashedFileField(blank=True, null=True, upload_to='program/map/', verbose_name='Схема (карта)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='schedule_file',
            field=events.fields.HashedFileField(blank=True, null=True, upload_to='program/schedule/', verbose_name='Расписание (файл)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='speakers_file',
            field=events.fields.HashedFileField(blank=True, null=True, upload_to='program/speakers/', verbose_name='Спикеры (файл)'),
        ),
    ]
