# Generated by Django 6.0.6 on 2026-07-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_user_is_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('order', 'name'), 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AddField(
            model_name='city',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
    ]
