# Generated by Django 6.0.6 on 2026-07-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_city_options_city_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='speakers_file',
        ),
        migrations.RemoveField(
            model_name='program',
            name='speakers_text',
        ),
        migrations.AddField(
            model_name='program',
            name='check_list',
            field=models.TextField(blank=True, verbose_name='Check-list'),
        ),
        migrations.AddField(
            model_name='program',
            name='faq',
            field=models.TextField(blank=True, verbose_name='FAQ'),
        ),
        migrations.AddField(
            model_name='program',
            name='map_description',
            field=models.TextField(blank=True, verbose_name='Описание карты проезда'),
        ),
    ]
