# Generated by Django 6.0.6 on 2026-07-09 23:30

import django.db.models.deletion
import events.fields
from django.db import migrations, models


def copy_schedule_files(apps, schema_editor):
    """Переносим существующий одиночный schedule_file в новую таблицу."""
    DayProgram = apps.get_model('events', 'DayProgram')
    DayScheduleFile = apps.get_model('events', 'DayScheduleFile')
    for day in DayProgram.objects.exclude(schedule_file='').exclude(
        schedule_file=None
    ):
        DayScheduleFile.objects.create(day=day, file=day.schedule_file.name, order=0)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_program_speakers_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayScheduleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', events.fields.HashedFileField(upload_to='day_program/schedule/', verbose_name='Расписание дня (файл)')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_files', to='events.dayprogram', verbose_name='Программа дня')),
            ],
            options={
                'verbose_name': 'Файл расписания дня',
                'verbose_name_plural': 'Файлы расписания дня',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.RunPython(copy_schedule_files, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='dayprogram',
            name='schedule_file',
        ),
        migrations.RemoveField(
            model_name='dayprogram',
            name='schedule_text',
        ),
    ]
