# Generated by Django 6.0.6 on 2026-07-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_dayprogram_schedule_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'permissions': [('access_panel', 'Доступ к панели управления')], 'verbose_name': 'Программа', 'verbose_name_plural': 'Программы'},
        ),
    ]
