# Generated by Django 6.0.6 on 2026-07-25 13:11

import events.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_program_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='faq_file',
            field=events.fields.HashedFileField(blank=True, null=True, upload_to='program/faq/', verbose_name='FAQ (файл)'),
        ),
    ]
